Repository team-dev-spring-2022/teamBanana, pull requests merged in 2022-03, with the labels that each got.

#51 #30 Подключена навигация, добавлены переходы между экранами
  App.js
  components/helloPage/HelloPage.js
  components/signInPage/SignInPage.js
Labels: enhancement

#52 #25 AppNavigator сделаны заголовки
  components/navigation/AppNavigator.js
  components/navigation/AppNavigatorStyle.js
Labels: enhancement

#53 #19 Добавил иконки приложения
  android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
Labels: wontfix

#60 #54 Добавлена заготовка страницы восстановления пароля
  components/navigation/AppNavigator.js
  components/navigation/AppNavigatorStyle.js
  components/recoveryPage/recoveryPage.js
  components/recoveryPage/recoveryPageStyle.js
  components/signInPage/SignInPage.js
Labels: enhancement

#63 Добавлена ссылка на репозиторий сервера в файл readme
  README.md
Labels: documentation

#64 Добавлен Apollo client
  components/apollo/apollo.js
  package-lock.json
  package.json
  yarn.lock
Labels: enhancement

#72 Добавлен запрос авторизации пользователя
  App.js
  components/apollo/apollo.js
  components/apollo/gqls/mutations.js
  components/signInPage/SignInPage.js
  metro.config.js
  package-lock.json
  package.json
  yarn.lock
Labels: enhancement
