Repository team-dev-spring-2022/teamBanana, pull requests merged in 2022-02, with the labels that each got.

#12 #7 Создана файловая структура проекта
  components/helloPage/HelloPage.js
  components/navigation/AppNavigator.js
  components/signInPage/SignInPage.js
  components/signUpPage/SignUpPage.js
  components/toDoListPage/ToDoListPage.js
Labels: good first issue

#13 #8 Изменина конфигурация Eslint
  .prettierrc.js
Labels: bug

#23 #20 Добавлены элементы страницы навигации
  components/navigation/AppNavigator.js
  components/navigation/AppNavigatorStyle.js
Labels: enhancement

#26 #22 Добавлены элементы страницы входа
  components/signInPage/SignInPage.js
  components/signInPage/SignInPageStyle.js
Labels: enhancement

#18 #17 Добавлены элементы начальный страницы
  components/helloPage/HelloPage.js
  components/helloPage/HelloPageStyle.js
Labels: enhancement

#34 #33 Добавлен шаблон страницы регистрации
  components/signUpPage/SignUpPage.js
  components/signUpPage/SignUpPageStyle.js
Labels: enhancement

#32 #29 Добавлены стили для начальной страницы
  App.js
  components/helloPage/HelloPageStyle.js
Labels: enhancement

#39 #35 Добавлен шаблон страницы с задачами
  components/toDoListPage/ToDoListPage.js
  components/toDoListPage/ToDoListPageStyle.js
Labels: enhancement

#38 #11 скорректировано наименование
  app.json
Labels: documentation

#45 #44 Исправил app.json
  app.json
Labels: bug

#46 #28 Добавлены элементы на страницу авторизации
  components/signInPage/SignInPage.js
Labels: enhancement

#47 #10 добовлено описание запуска
  README.md
Labels: documentation

#48 #27 Добавлены стили для страницы входа
  components/signInPage/SignInPageStyle.js
Labels: enhancement

#49 #24 Добавлен Native Stack Navigator
  components/navigation/AppNavigator.js
  package-lock.json
  package.json
  yarn.lock
Labels: enhancement
