Repository team-dev-spring-2022/teamBanana, pull requests merged in 2022-04, with the labels that each got.

#73 Добавлен запрос для регистрации пользователя
  components/apollo/gqls/mutations.js
Labels: enhancement

#74 Авторизация пользователя
  components/apollo/gqls/mutations.js
  components/signInPage/SignInPage.js
Labels: enhancement

#79 Добавлен вывод списка задач
  components/apollo/gqls/queries.js
  components/toDoListPage/ToDoListPage.js
Labels: enhancement

#81 Внесены правки в стиль
  components/recoveryPage/recoveryPage.js
  components/recoveryPage/recoveryPageStyle.js
  components/signUpPage/SignUpPageStyle.js
Labels: bug

#94 Добавлен запрос для добавления задач
  components/apollo/gqls/mutations.js
Labels: enhancement

#98 #42 Добавлены стили для страницы списка задач
  components/toDoListPage/ToDoListPage.js
  components/toDoListPage/ToDoListPageStyle.js
  package-lock.json
  package.json
  yarn.lock
Labels: enhancement

#103 #83 Добавлен запрос для редактирования задач
  components/apollo/gqls/mutations.js
Labels: enhancement

#107 #86 Добавлена функция добавления задач
  components/createTasksPage/CreateTasksPage.js
Labels: enhancement

#108 #84 Добавлен запрос для удаления задачи
  components/apollo/gqls/mutations.js
Labels: enhancement

#110 #85 AsyncStorage и передача данных между экранами
  components/createTasksPage/CreateTasksPage.js
  components/helloPage/HelloPage.js
  components/signInPage/SignInPage.js
  components/signUpPage/SignUpPage.js
  components/toDoListPage/ToDoListPage.js
Labels: enhancement

#112 #88 Функционал для редактирования задач
  components/changeTaskPage/ChangeTaskPage.js
  components/toDoListPage/ToDoListPage.js
Labels: enhancement

#113 #87 Добавлен функционал для удаления задач
  components/changeTaskPage/ChangeTaskPage.js
  components/changeTaskPage/ChangeTaskPageStyle.js
Labels: enhancement

#115 #114 Добавлена возможность выполнения задачи на странице редактирования
  components/changeTaskPage/ChangeTaskPage.js
  components/changeTaskPage/ChangeTaskPageStyle.js
  components/createTasksPage/CreateTasksPage.js
  components/createTasksPage/CreateTasksPageStyle.js
  components/toDoListPage/ToDoListPage.js
  components/toDoListPage/ToDoListPageStyle.js
Labels: enhancement

#117 #116 Добавлено выполнение задач из списка задач
  components/toDoListPage/ToDoListPage.js
Labels: enhancement

#121 #119 добавлен логотип в readme
  README.md
Labels: documentation
